apiVersion: v1
kind: Secret
metadata:
  name: {{ include "algorycode-qr-service.fullname" . }}-secret
  labels:
    {{- include "algorycode-qr-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secret.data.springDatasourceUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.data.springDatasourcePassword | quote }}
