replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: tarikhamarat/algorycode-rent-service
  tag: 25acbf7
  pullPolicy: Always

imagePullSecrets: []

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  annotations: {}

spring:
  applicationName: algorycode-rent-service
  jpa:
    ddlAuto: validate
    showSql: "false"

rabbitmq:
  host: rabbitmq.algorycode.com
  port: "5672"
  virtualHost: "/"

app:
  cors:
    enabled: false
    allowedOriginPatterns: "*"
  mail:
    rabbit:
      exchange: algorycode.mail.exchange
      routingKey: mail.send.requested
      queueDlq: algorycode.mail.work-queue.dlq
  rentalRequest:
    greenInsuranceFee: "75.00"
  contract:
    templatePath: ""
    outputDir: /app/generated-contracts
    pdfLineVatPercent: "20"
    authorization:
      taxablePersonName: "KURU GLOBAL"
      niptNumber: "M51406058A"
      representativeName: "TARIK KURU"
      representativeBirthPlace: "ISTANBUL"
      representativeResidence: "TIRAN"
      representativeBirthDate: "21/07/2000"
      representativePassportNo: "U36724300"
      footerCompany: "KURU GLOBAL"
      footerAddress: "RINAS AIRPORT - Rinas, Albania."
      roadsideAssistancePhone: "+90 510 220 553"
  whatsapp:
    enabled: "true"
    adminPhoneE164: "905312187455"
    webhookUrl: ""
    webhookAuthBearer: ""
    callmebotApiKey: ""
  objectStorage:
    enabled: "true"
    endpoint: "https://s3.algorycode.com"
    bucket: "rent"
    keyPrefix: "prod"
    presignExpirySeconds: "3600"

logging:
  levelRent: INFO

secret:
  data:
    springRabbitmqUsername: CHANGEME
    springRabbitmqPassword: CHANGEME
    appObjectStorageAccessKey: CHANGEME
    appObjectStorageSecretKey: CHANGEME

extraEnv: []

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

podSecurityContext: {}
securityContext: {}

probes:
  startup:
    path: /actuator/health/liveness
    failureThreshold: 60
    periodSeconds: 5
    timeoutSeconds: 10
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    initialDelaySeconds: 90
    periodSeconds: 20
    timeoutSeconds: 5

ingress:
  enabled: false
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: rent.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: rent-example-tls
      hosts:
        - rent.example.com
