apiVersion: v1
kind: Secret
metadata:
  name: {{ include "algorycode-rent-auth-service.fullname" . }}-secret
  labels:
    {{- include "algorycode-rent-auth-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secret.data.springDatasourceUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.data.springDatasourcePassword | quote }}
  SPRING_RABBITMQ_USERNAME: {{ .Values.secret.data.springRabbitmqUsername | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.secret.data.springRabbitmqPassword | quote }}
  SPRING_SECURITY_JWT_SECRET: {{ .Values.secret.data.springSecurityJwtSecret | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: {{ .Values.secret.data.googleOAuthClientSecret | quote }}
