replicaCount: 1

image:
  repository: tarikhamarat/algorycode-gateway
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080
  annotations: {}

gateway:
  routes:
    - id: algorycode-rent-service
      path: /api/**
      service:
        name: algorycode-rent-service-prod
        namespace: algory-prod
        port: 8090
        scheme: http
        clusterDomain: cluster.local

ingress:
  enabled: false

extraEnv: []
